name: LuaRocks release
on:
  push:
    tags: # Will upload to luarocks.org when a tag is pushed
      - "*"
jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@v9
      - uses: leafo/gh-actions-luarocks@v4
      - name: Install dkjson
        run: luarocks install dkjson
      - name: Upload to luarocks
        run: luarocks upload kong-event-pub*.rockspec --api-key=$LUAROCKS_API_KEY --force
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
